const goods = [
  {
    id: "0001",
    name: "Флюїд для обличчя для сухої шкіри",
    image: "./img/product_1.png",
    discription:
      "При регулярному використанні колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 630,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0002",
    name: "Антиоксидантний крем для обличчя",
    image: "./img/product_2.png",
    discription:
      "При регулярному використанні антиоксидантного крему, колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 850,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0003",
    name: "Гель для вмивання для проблемної шкіри",
    image: "./img/product_3.png",
    discription:
      "При регулярному використанні геля для вмивання обличчя, колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 590,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0004",
    name: "Зволожуюча сироватка для нормальної шкіри",
    image: "./img/product_4.png",
    discription:
      "При регулярному використанні зволожуючої сироватки, колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 480,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0005",
    name: "Зволожуючий крем для сухої шкіри",
    image: "./img/product_5.png",
    discription:
      "При регулярному використанні зволожуючого крему для сухої шкіри колір обличчя стане більш рівномірним і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 830,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0006",
    name: "Тонік для обличчя для нормальної шкіри",
    image: "./img/product_6.png",
    discription:
      "При регулярному використанні колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 450,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0007",
    name: "Пінка для очищення шкіри обличчя",
    image: "./img/product_7.png",
    discription:
      "При регулярному використанні пінки колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 560,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0008",
    name: "Набір Денний та нічний крем",
    image: "./img/product_8.png",
    discription:
      "При регулярному використанні колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 1230,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0009",
    name: "Матуючий денний крем для жиної шкіри",
    image: "./img/product_9.png",
    discription:
      "При регулярному використанні матуючого крему колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 680,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0010",
    name: "Нічний антивіковий крем для сухої шкіри",
    image: "./img/product_10.png",
    discription:
      "При регулярному використанні колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 860,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0011",
    name: "Гель для зняття макіяжу",
    image: "./img/product_11.png",
    discription:
      "Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 730,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0012",
    name: "Антивікова сироватка для зони навколо очей",
    image: "./img/product_12.png",
    discription:
      "При регулярному використанні колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 900,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0013",
    name: "Лосьон для нормальної та комбінованої шкіри",
    image: "./img/product_13.png",
    discription:
      "При регулярному використанні колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча.",
    price: 1050,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0014",
    name: "Скраб для чутливої шкіри",
    image: "./img/product_14.png",
    discription:
      "При регулярному використанні колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 890,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
  {
    id: "0015",
    name: "Гель для очищення шкіри обличчя",
    image: "./img/product_15.png",
    discription:
      "При регулярному використанні колір обличчя стане більш рівномірним, а почервоніння і сухість менш вираженими. Крем попереджає появу зморшок, зневоднення і стоншування шкіри за допомогою потужних антиоксидантів з екстракту швейцарської сосни й чаю матча. Велика кількість протизапальних і протиалергійних компонентів допомагає позбутися подразнень і гіперчутливості.",
    price: 890,
    composition:
      "Aqua (вода), Grape Seed (Vitis Vinifera) Oil (олія виноградної кісточки), Triolein, Glyceryl Dioleate, Polyglyceryl-3 Cetyl Ether (емульгатор з оливкової олії), Butyrospermum Parkii (Shea) Butter (баттер ши (каріте)), Cetearyl Alcohol (цетилстеариловий спирт), Complex of phytoе strogens: Glycine Soja Extract, Trifolium Pratense Extract, Tamarindus Indica Fruit Extract, Medicago Sativa Extract, Glycyrrhiza glabra Root Extract, Vitis Vinifera Leaf Extract, Humulus Lupulus Cone Extract (комплекс фітоестрогенів: екстракти сої, конюшини, фініка, люцерни, солодки, червоного винограду, хмелю), Optiphen BD* (харчовий консервант), Limnanthes Alba (Meadowfoam) Seed Oil (олія пінника), Сhaulmoogra (Hydnocarpus laurifolia) Seed Oil (чаульмугри олія), Carapa Guianensis Seed Oil (олія андироби), Pinus Sylvestris Bark Extract (екстракт швейцарської кам’яної сосни), Lactose, Milk Protein (молочні поліпептиди), Vitamin E (Вітамін Е), Blend of Essential Oils: Ylang Ylang (Cananga odorata) Flower Oil, Neroli (Citrus aurantium var. amara) Essential Oil, Patchouli (Pogostemon Cablin Blanco) Essential Oil, Cinnamon Bark (Cinnamomum verum) Essential Oil, Grapefruite (Citrus paradisi) Essential Oil, European mandarin (Citrus mandurensis) Essential Oil, Citrus Aurantium Dulcis Peel Extract, Rosa centifolia Flower Extract (композиція натуральних ефірних олій: іланг – ілангу, неролі, пачулі, кориці, грейпфрута, мандарина, апельсина, абсолют троянди), Camellia Sinensis Leaf Extract (екстракт чаю матча), Beta Glucan (бета-глюкан), (Coenzyme Q10) Ubiquinone (Коензим Q10). *Сертифікат Ecocert.",
  },
];

localStorage.setItem("goods", JSON.stringify(goods));
